# # Файл main.yml
# # Имя workflow
# name: Main Taski Workflow
# # Перечень событий-триггеров, при которых должен запускаться workflow
# on:
#   # Событие push возникает,
#   # когда изменения исходного кода приходят на сервер GitHub
#   push:
#     # Отслеживаем изменения только в ветке main
#     branches:
#       - main
# # Перечень задач
# jobs:
#   # Единственная задача — склонировать код 
#   # и вывести в консоль дерево файлов
#   checkout-and-print-tree:
#     runs-on: ubuntu-latest
#     steps:
#       # На GitHub Actions есть готовые описания шагов, 
#       # их можно использовать в своих workflow.
#       # Применим готовое описание шага для получения исходного кода
#       - name: Check out repository code  # Имя шага задаём сами
#         uses: actions/checkout@v3  # Берём готовое решение из библиотеки GitHub Actions
#       # Выполняем команду tree в текущей директории
#       - name: Print project tree
#         run: tree .

# .github/workflows/main.yml
# .github/workflows/main.yml
name: Main Taski workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Чтобы запустить тесты, нужно установить зависимости
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install flake8==6.0.0 flake8-isort==6.0.0
        pip install -r ./backend/requirements.txt 
    # Этот шаг дополним:
    - name: Test with flake8 and django tests
      # Команд стало больше одной; ставим символ | и пишем команды построчно
      run: |
        python -m flake8 backend/
        cd backend/
        python manage.py test
